parameters:
    elvis_connector.factory.elvis_collection.class:                 Fot\Component\ElvisConnector\Factory\ElvisCollectionFactory


services:
    elvis_connector.factory.elvis_collection:
        class: '%elvis_connector.factory.elvis_collection.class%'
        arguments:
            - '@pim_catalog.repository.locale'
            - '%elvis_connector.model.elvis_collection.class%'