extensions:
    fot-elvis-system-configuration:
        module: fot/elvisconnector/form/system
        parent: oro-system-config-system
        targetZone: content
        position: 130

    fotelvis-product-asset-picker-form:
        module: fotelvisconnector/js/picker/elvis-asset-grid
attribute_fields:
    fot-elvis-asset-collection-field: fot/elvis-asset-collection-field