oro_menu_config:
    items:
        elivis_menu:
            label: 'Elvis'
            uri: '#'
            extras :
                position: 2
        elvis_search:
            label: 'Recherche'
            route: elvis_connector_search
        elvis_index:
            label: 'Formulaire Popup'
            route: elvis_connector_index
    tree:
        application_menu:
            children:
                elivis_menu:
                    children:
                        elvis_index : ~
                        elvis_search: ~
oro_titles:
    elvis_connector_search: 'Recherche'
    elvis_connector_index: 'Formulaire Popup'