config:
    paths:
        fot/elvis-asset-collection-field: fotelvisconnector/js/product/field/fot-elvis-assets-collection
        fot/template/product/field/elvis-asset-collection: fotelvisconnector/templates/product/field/fot-elvis-assets-collection.html