fot_elvis_product_asset_rest_index:
    path: /rest/
    defaults: { _controller: FotElvisConnectorBundle:Actions:index, _format: json }
    methods: [GET]
    options:
        expose: true
elvis_connector_search:
    path:     /elvis-search
    defaults: { _controller: FotElvisConnectorBundle:Actions:searchAsset }
    options:
        expose: true

elvis_connector_get_categorie:
    path:     /elvis-categorie
    defaults: { _controller: FotElvisConnectorBundle:Actions:getCategorie , _format: json }
    options:
        expose: true

elvis_connector_get_categorie_roots:
    path:     /elvis-categorie-roots
    defaults: { _controller: FotElvisConnectorBundle:Actions:getCategorieRoots , _format: json }
    options:
        expose: true

elvis_connector_get_categorie_content:
    path:     /elvis-categorie-content
    defaults: { _controller: FotElvisConnectorBundle:Actions:getCategorieContent , _format: json }
    options:
        expose: true

elvis_connector_update_product:
    path:     /elvis-product-update
    defaults: { _controller: FotElvisConnectorBundle:Actions:setProductAsset }
    options:
        expose: true

elvis_connector_assets_product:
    path:     /elvis-get-product-assets
    defaults: { _controller: FotElvisConnectorBundle:Actions:getProductAssets , _format: json }
    options:
        expose: true
elvis_connector_test:
    path:     /test
    defaults: { _controller: FotElvisConnectorBundle:Actions:test , _format: json }
    options:
        expose: true